version: '3.8'

services:
  personaapi-dotnet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"  # Mapea el puerto 80 del contenedor al 8080 del host
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=arq_per_db;User Id=sa;Password=YourSecurePassword123!;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=YourSecurePassword123!
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Montar el script de inicialización
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mssql_data:
