version: '3.8'

services:
  dotnet:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5062:5062"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=arq_per_db;User=sa;Password=YourSecurePassword123!;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - my_network

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourSecurePassword123!
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init.sql:/usr/src/app/init.sql
      - ./entrypoint.sh:/usr/src/app/entrypoint.sh
    networks:
      - my_network
    user: root
    entrypoint: /bin/bash -c "apt-get update && apt-get install -y mssql-tools unixodbc-dev && /usr/src/app/entrypoint.sh"

networks:
  my_network:
    driver: bridge

volumes:
  mssql_data:
    driver: local
