version: '3.8'

services:
  subscripto-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80" # Mapea el puerto HTTP de la aplicación
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=taller;User=sa;Password=Your_password123;TrustServerCertificate=True;
    depends_on:
      - db
    networks:
      - my_network # Añadido para permitir la comunicación en la red

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Your_password123
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433" # Mapea el puerto SQL Server
    volumes:
      - mssql_data:/var/opt/mssql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mssql_data: